name: hackutd
description: "A new Flutter project."

# Prevent accidental publishing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  http: ^1.5.0

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  firebase_database: ^11.1.0

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
